/**
 * UI mikrocopy (11 §0.3: smije se pisati sam). Bez tvrdnji o studiju.
 */
export const ui = {
  skipToContent: "Skip to content",
  skipIntro: "Skip intro",
  scrollHint: "Scroll",
  menu: "Menu",
  close: "Close",
  dragHint: "Drag the hand or head to pose · drag the stage to turn",
  dragHintTouch: "Touch to look inside · drag to turn",
  reelPlaceholder: "Placeholder",
  reelFilterLabel: "Filter reels",
  faqToggle: "Toggle answer",
  backHome: "Back to the stage",
  form: {
    step: (n: number, total: number) => `Step ${n} of ${total}`,
    next: "Next",
    back: "Back",
    send: "Send brief",
    sending: "Sending…",
    typeLegend: "What are we making?",
    typeOther: "Not sure yet",
    productLabel: "Product or brand",
    productHint: "What are we building the world around?",
    projectLabel: "The project",
    projectHint: "A few lines are enough: the idea, where it will run, any dates.",
    nameLabel: "Your name",
    emailLabel: "Email",
    required: "Required",
    errType: "Choose one option to continue.",
    errProduct: "Tell us the product or brand.",
    errProject: "A few words about the project, please.",
    errName: "Please add your name.",
    errEmail: "That email address doesn't look complete.",
    sentTitle: "Thank you.",
    sentBody: "Your brief is on its way.",
    previewTitle: "This is a preview.",
    previewBody: "The form isn't connected yet, so nothing was sent. Your text stayed in this browser.",
    errorTitle: "Something went wrong.",
    errorBody: "The brief wasn't sent. Please try again in a moment.",
  },
} as const;
